In [1]:
import numpy as np
a=np.array([12,4,56,7,29,10])
print("Original array:",a,"\nSorted array:",np.sort(a))

Original array: [12  4 56  7 29 10] 
Sorted array: [ 4  7 10 12 29 56]


In [3]:
b=np.array([[12,4,56],[7,29,10],[5,3,0]])
print(np.sort(b))
print(np.sort(b,axis=0))

[[ 4 12 56]
 [ 7 10 29]
 [ 0  3  5]]
[[ 5  3  0]
 [ 7  4 10]
 [12 29 56]]


In [5]:
import pandas as pd
l=[10,20,30]
print(pd.Series(l))

0    10
1    20
2    30
dtype: int64


In [7]:
dd={"Name":["Alice","Bob","Charlie","David"],"Age":[24,27,22,32],"Department":["HR","Finance","IT","Marketing"],
    "Salary":[50000,60000,55000,65000]}
d=pd.DataFrame(dd)
print(pd.DataFrame(d))

      Name  Age Department  Salary
0    Alice   24         HR   50000
1      Bob   27    Finance   60000
2  Charlie   22         IT   55000
3    David   32  Marketing   65000


In [9]:
print(d.loc[0])

Name          Alice
Age              24
Department       HR
Salary        50000
Name: 0, dtype: object


In [11]:
print(d.loc[0:2])

      Name  Age Department  Salary
0    Alice   24         HR   50000
1      Bob   27    Finance   60000
2  Charlie   22         IT   55000


In [13]:
print(d['Age'])

0    24
1    27
2    22
3    32
Name: Age, dtype: int64


In [15]:
print(d["Name"])

0      Alice
1        Bob
2    Charlie
3      David
Name: Name, dtype: object


In [17]:
d.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   Name        4 non-null      object
 1   Age         4 non-null      int64 
 2   Department  4 non-null      object
 3   Salary      4 non-null      int64 
dtypes: int64(2), object(2)
memory usage: 260.0+ bytes


In [19]:
d.describe()

Age        Salary
count   4.000000      4.000000
mean   26.250000  57500.000000
std     4.349329   6454.972244
min    22.000000  50000.000000
25%    23.500000  53750.000000
50%    25.500000  57500.000000
75%    28.250000  61250.000000
max    32.000000  65000.000000

In [81]:
df

Robot_ID   Task_Type Component_ID     Sensor_Type            Sensor_Data  \
0    RBT_001  Inspection      CMP_460           LIDAR  1 (obstacle detected)   
1    RBT_002    Assembly      CMP_252         Thermal             85.3 (°C)   
2    RBT_003  Inspection      CMP_248         Thermal       92% (visual fit)   
3    RBT_004     Welding      CMP_433          Camera      98% (defect-free)   
4    RBT_005    Assembly      CMP_992          Camera       92% (visual fit)   
..       ...         ...          ...             ...                    ...   
495  RBT_496  Inspection      CMP_834           LIDAR             85.3 (°C)   
496  RBT_497  Inspection      CMP_851           LIDAR       92% (visual fit)   
497  RBT_498  Inspection      CMP_657           LIDAR             82.4 (°C)   
498  RBT_499    Assembly      CMP_562          Camera      98% (defect-free)   
499  RBT_500    Assembly      CMP_465  LIDAR + Camera             75.8 (°C)   

     Processing_Time (s)  Accuracy (%) Environmental_Status  \
0                   67.0          90.4               Stable   
1                   71.2          98.1               Stable   
2                   49.2          95.3             Unstable   
3                   74.5          90.2               Stable   
4                   64.5          97.2             Unstable   
..                   ...           ...                  ...   
495                 66.3          96.2             Unstable   
496                 45.1          92.8             Unstable   
497                 75.4          98.7             Unstable   
498                 48.7          94.9               Stable   
499                 73.5          91.4               Stable   

     Energy_Consumption (kWh) Human_Intervention_Needed Obstacle_Detected  \
0                         2.2                        No               Yes   
1                         2.7                       Yes                No   
2                         2.4                        No                No   
3                         2.4                       Yes                No   
4                         1.8                        No                No   
..                        ...                       ...               ...   
495                       1.3                        No               Yes   
496                       2.3                        No               Yes   
497                       2.6                       Yes                No   
498                       2.2                        No               Yes   
499                       2.0                       Yes                No   

    Defect_Detected  
0               Yes  
1                No  
2                No  
3               Yes  
4                No  
..              ...  
495              No  
496             Yes  
497              No  
498              No  
499             Yes  

[500 rows x 12 columns]

In [83]:
df=pd.read_excel("robot_dataset.xlsx")
df.head()


Robot_ID   Task_Type Component_ID Sensor_Type            Sensor_Data  \
0  RBT_001  Inspection      CMP_460       LIDAR  1 (obstacle detected)   
1  RBT_002    Assembly      CMP_252     Thermal             85.3 (°C)   
2  RBT_003  Inspection      CMP_248     Thermal       92% (visual fit)   
3  RBT_004     Welding      CMP_433      Camera      98% (defect-free)   
4  RBT_005    Assembly      CMP_992      Camera       92% (visual fit)   

   Processing_Time (s)  Accuracy (%) Environmental_Status  \
0                 67.0          90.4               Stable   
1                 71.2          98.1               Stable   
2                 49.2          95.3             Unstable   
3                 74.5          90.2               Stable   
4                 64.5          97.2             Unstable   

   Energy_Consumption (kWh) Human_Intervention_Needed Obstacle_Detected  \
0                       2.2                        No               Yes   
1                       2.7                       Yes                No   
2                       2.4                        No                No   
3                       2.4                       Yes                No   
4                       1.8                        No                No   

  Defect_Detected  
0             Yes  
1              No  
2              No  
3             Yes  
4              No

In [85]:
df.describe()

Processing_Time (s)  Accuracy (%)  Energy_Consumption (kWh)
count           500.000000    500.000000                500.000000
mean             59.937000     94.920600                  2.014000
std              11.688808      2.900949                  0.582789
min              40.100000     90.000000                  1.000000
25%              49.675000     92.500000                  1.500000
50%              59.600000     94.900000                  2.000000
75%              70.000000     97.500000                  2.500000
max              80.000000     99.900000                  3.000000

In [87]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 12 columns):
 #   Column                     Non-Null Count  Dtype  
---  ------                     --------------  -----  
 0   Robot_ID                   500 non-null    object 
 1   Task_Type                  500 non-null    object 
 2   Component_ID               500 non-null    object 
 3   Sensor_Type                500 non-null    object 
 4   Sensor_Data                500 non-null    object 
 5   Processing_Time (s)        500 non-null    float64
 6   Accuracy (%)               500 non-null    float64
 7   Environmental_Status       500 non-null    object 
 8   Energy_Consumption (kWh)   500 non-null    float64
 9   Human_Intervention_Needed  500 non-null    object 
 10  Obstacle_Detected          500 non-null    object 
 11  Defect_Detected            500 non-null    object 
dtypes: float64(3), object(9)
memory usage: 47.0+ KB


In [89]:
df.loc[0:4]

Robot_ID   Task_Type Component_ID Sensor_Type            Sensor_Data  \
0  RBT_001  Inspection      CMP_460       LIDAR  1 (obstacle detected)   
1  RBT_002    Assembly      CMP_252     Thermal             85.3 (°C)   
2  RBT_003  Inspection      CMP_248     Thermal       92% (visual fit)   
3  RBT_004     Welding      CMP_433      Camera      98% (defect-free)   
4  RBT_005    Assembly      CMP_992      Camera       92% (visual fit)   

   Processing_Time (s)  Accuracy (%) Environmental_Status  \
0                 67.0          90.4               Stable   
1                 71.2          98.1               Stable   
2                 49.2          95.3             Unstable   
3                 74.5          90.2               Stable   
4                 64.5          97.2             Unstable   

   Energy_Consumption (kWh) Human_Intervention_Needed Obstacle_Detected  \
0                       2.2                        No               Yes   
1                       2.7                       Yes                No   
2                       2.4                        No                No   
3                       2.4                       Yes                No   
4                       1.8                        No                No   

  Defect_Detected  
0             Yes  
1              No  
2              No  
3             Yes  
4              No

In [91]:
df.tail()

Robot_ID   Task_Type Component_ID     Sensor_Type        Sensor_Data  \
495  RBT_496  Inspection      CMP_834           LIDAR         85.3 (°C)   
496  RBT_497  Inspection      CMP_851           LIDAR   92% (visual fit)   
497  RBT_498  Inspection      CMP_657           LIDAR         82.4 (°C)   
498  RBT_499    Assembly      CMP_562          Camera  98% (defect-free)   
499  RBT_500    Assembly      CMP_465  LIDAR + Camera         75.8 (°C)   

     Processing_Time (s)  Accuracy (%) Environmental_Status  \
495                 66.3          96.2             Unstable   
496                 45.1          92.8             Unstable   
497                 75.4          98.7             Unstable   
498                 48.7          94.9               Stable   
499                 73.5          91.4               Stable   

     Energy_Consumption (kWh) Human_Intervention_Needed Obstacle_Detected  \
495                       1.3                        No               Yes   
496                       2.3                        No               Yes   
497                       2.6                       Yes                No   
498                       2.2                        No               Yes   
499                       2.0                       Yes                No   

    Defect_Detected  
495              No  
496             Yes  
497              No  
498              No  
499             Yes

In [102]:
df["Robot_ID"]

0      RBT_001
1      RBT_002
2      RBT_003
3      RBT_004
4      RBT_005
        ...   
495    RBT_496
496    RBT_497
497    RBT_498
498    RBT_499
499    RBT_500
Name: Robot_ID, Length: 500, dtype: object

In [174]:
df.loc[212:237]

Robot_ID   Task_Type Component_ID     Sensor_Type            Sensor_Data  \
212  RBT_213    Painting      CMP_622           LIDAR             82.4 (°C)   
213  RBT_214  Inspection      CMP_215  LIDAR + Camera       92% (visual fit)   
214  RBT_215    Painting      CMP_570           LIDAR         0 (clear path)   
215  RBT_216     Welding      CMP_101         Thermal             85.3 (°C)   
216  RBT_217     Welding      CMP_959           LIDAR             75.8 (°C)   
217  RBT_218     Welding      CMP_226         Thermal  1 (obstacle detected)   
218  RBT_219     Welding      CMP_193          Camera       92% (visual fit)   
219  RBT_220    Assembly      CMP_167         Thermal  1 (obstacle detected)   
220  RBT_221     Welding      CMP_725  LIDAR + Camera        0 (no obstacle)   
221  RBT_222    Painting      CMP_506          Camera         0 (clear path)   
222  RBT_223  Inspection      CMP_135  LIDAR + Camera             82.4 (°C)   
223  RBT_224     Welding      CMP_474          Camera             75.8 (°C)   
224  RBT_225     Welding      CMP_551           LIDAR      98% (defect-free)   
225  RBT_226  Inspection      CMP_900  LIDAR + Camera             82.4 (°C)   
226  RBT_227    Painting      CMP_548         Thermal       92% (visual fit)   
227  RBT_228    Painting      CMP_824           LIDAR        0 (no obstacle)   
228  RBT_229     Welding      CMP_844         Thermal             82.4 (°C)   
229  RBT_230    Painting      CMP_110         Thermal             82.4 (°C)   
230  RBT_231    Assembly      CMP_187  LIDAR + Camera         0 (clear path)   
231  RBT_232     Welding      CMP_821         Thermal  1 (obstacle detected)   
232  RBT_233  Inspection      CMP_543          Camera       92% (visual fit)   
233  RBT_234     Welding      CMP_632         Thermal        0 (no obstacle)   
234  RBT_235     Welding      CMP_376         Thermal             75.8 (°C)   
235  RBT_236  Inspection      CMP_260         Thermal         0 (clear path)   
236  RBT_237     Welding      CMP_949  LIDAR + Camera      98% (defect-free)   
237  RBT_238    Painting      CMP_174         Thermal             82.4 (°C)   

     Processing_Time (s)  Accuracy (%) Environmental_Status  \
212                 67.7          92.6             Unstable   
213                 58.0          98.8             Unstable   
214                 64.4          92.3             Unstable   
215                 68.2          96.2             Unstable   
216                 79.5          91.2               Stable   
217                 72.3          97.3             Unstable   
218                 59.5          94.1             Unstable   
219                 43.1          98.5             Unstable   
220                 75.7          99.6               Stable   
221                 58.8          99.4             Unstable   
222                 66.2          90.4             Unstable   
223                 44.9          91.3             Unstable   
224                 67.2          99.4             Unstable   
225                 61.7          97.4               Stable   
226                 75.9          98.9               Stable   
227                 59.5          91.1               Stable   
228                 46.0          98.3             Unstable   
229                 78.6          90.4               Stable   
230                 53.2          90.3             Unstable   
231                 66.4          90.1               Stable   
232                 64.6          90.5             Unstable   
233                 46.7          94.1             Unstable   
234                 53.7          94.4               Stable   
235                 61.0          93.4               Stable   
236                 44.1          91.1               Stable   
237                 70.5          97.3               Stable   

     Energy_Consumption (kWh) Human_Intervention_Needed Obstacle_Detected  \
212                       1.4                        No         